### ISSUE TITLE
Smart Web3 client

### ISSUE THREAD

**Issue by superbeefyboy** [beefyfinance/beefy-api#103]
# Context
At our current rate, we are adding a dozen of strats per week to the system. This is making us hit the ratelimit on initialization.

A naive solution could be to group the requests, by splitting the pools in batches and waiting between them.
This approach has the problem that it relies on initialization order, or "knowing" the network rules from the application layer.

# Proposed solution
Wrap the web3 object into a new object that understands the rules of each network. This object should keep track of the amount of request per minute / second and insert delays between them as needed.

The entry point for this solution would be src/utils/web3.js where the multiple clients are initialized.
we could replace: `new Web3(endpoint)`  with  `new Web3(endpoint, ratelimit)`.

**Comment by wivern-co-uk** [comment]
Hey @superbeefyboy, there is another way to sort it out with refactoring APY code, reducing redundant RPC calls and batching the requests. No need to build optimisation layer on top of slow foundation. I'll take over on solving the root cause issue.

On it.
