### ISSUE TITLE
/apy api details

### ISSUE THREAD

**Issue by xbotuk** [beefyfinance/beefy-api#129]
/apy api does not provide much information other than just the name of the asset and APY, but can you please add other tags like TVL, Display Name, Platform, Vault type, Asset 1 & 2 (if any) and whether deposit is paused

having these available in the endpoint will minimise traffic on your host and also simplify my analysis. Thanks

**Comment by superbeefyboy** [comment]
This is not an issue with the api. Is a use case you would desire, but is not part of the API use case.
If you want to implement it, you can fork the repository, run it and add the desired functionality.

**Comment by xbotuk** [comment]
Can you please point me to the area of the code/files and I can try making the changes?
