### ISSUE TITLE
/apy/breakdown vaultApr should include performance fee

### ISSUE THREAD

**Issue by ReflectiveChimp** [beefyfinance/beefy-api#245]
To have consistency between the Apy and Apr, the `vaultApr` in the apy breakdown endpoint should be returned with the vault-specific performance fee deducted.

Optionally something like `vaultSimpleApr` could be added to keep the underlying farm Apr exposed, however this is not needed for the UI.

**Comment by MirthFutures** [comment]
Fixed with commit d093c1f6e0daa36e1a05575491a6c4beb372db5d
