### ISSUE TITLE
Stop relying on Pancakeswap API for price data

### ISSUE THREAD

**Issue by sirbeefalot** [beefyfinance/beefy-api#36]
We are looking to make the API more reliable. One of our current pain points is that most of our price information comes from https://api.pancakeswap.finance/api/v1/price 

We have constant issues with the endpoint being unreliable. 

It would benefit us to get those prices directly from the Pancakeswap contracts.

**Comment by wivern-co-uk** [comment]
Hey @sirbeefalot, did an investigation and that's quite a refactoring, so I want to align with you on the plan first.


Idea is to enrich `lpTokenPrices` with BNB price data and extrapolate the rest of the prices based on LP balances, considering LP token wage is always 50/50. If there will be another wage at some point, we would need to make this data part of `*Pools.json`. It will be something like `getNyanswopTokenPrices` but reusable. Such approach will allow to get rid of both issues (this and #37) and would make adding new AMM oracles a breeze. WDYT?

**Comment by wivern-co-uk** [comment]
On it...

**Comment by wivern-co-uk** [comment]
Looking forward for a review @sirbeefalot
