### ISSUE TITLE
Stop relying on Streetswap API for price data

### ISSUE THREAD

**Issue by sirbeefalot** [beefyfinance/beefy-api#37]
We are looking to make the API more reliable. One of our current pain points is our reliance on third party APIs that are sometimes out of service. For example all our Thugs price stats comes from their API at https://api.beefy.finance/thugs/tickers

It would benefit us to get those prices directly from the Streetswap contracts.

**Comment by wivern-co-uk** [comment]
I think this is outdated since https://github.com/beefyfinance/beefy-api/commit/2a6ecfc4ad07c71fa1c202eea0668dda107f273f we rather need to retire calls to https://api.beefy.finance/thugs/tickers from https://github.com/beefyfinance/beefy-app side

**Comment by sirbeefalot** [comment]
You're right. This was solved by your PR https://github.com/beefyfinance/beefy-api/pull/52
