### ISSUE TITLE
Curve LP token price

### ISSUE THREAD

**Issue by gabrielfior** [beefyfinance/beefy-api#461]
Using the endpoint /lps, one can fetch all the LP prices crosschain. Below you can find a subset of the response:

```json
"curve-poly-atricrypto3": 1938.4656787747067
```

Could you please explain where the value 1938.46 comes from? I cannot derive this calculation from any value displayed on the curve website pool (https://polygon.curve.fi/atricrypto3). Thank you!

**Comment by sircryptomaxi** [comment]
It come from counting how many USDT, ETH and WBTC are on the LP contract, multiply by the price of each of those tokens and divide by the total supply of LP. That price is how much 1 LP token is worth. 

https://github.com/beefyfinance/beefy-api/blob/master/src/api/stats/common/curve/getCurvePricesCommon.js

**Comment by gabrielfior** [comment]
Thank you very much, that answers my question.
