### ISSUE TITLE
tvl endpoint is missing in docs (README) 

### ISSUE THREAD

**Issue by pmorange** [beefyfinance/beefy-api#766]
Hi,

Seems like the tvl endpoint is working, but there is no mention of it in the docs. 

Furthermore, what is the output format ?

I see the following for example :
```
{
  "25": {
     ...
  },
  "56": {
     ...
   },
  "137": {
     ...
  }
}
```

What do these numbers mean ?

Thanks

**Comment by AllTradesz** [comment]
Hi. The "numbers" you reference are the "Chain ID"s of the blockchains on which the Beefy vault contracts have been deployed.

Btw, the most active place to discuss aspects of Beefy's protocol is in the Beefy discord, the #development channel in this case.

**Comment by pmorange** [comment]
Thanks, thought about discord but didn't know if this was too specific...
Shall I close this then, or leave it until info is in the README ?
